### ISSUE TITLE
Point to Faucets

### ISSUE THREAD

**Issue by CarlBeek** [ethereum/eth2.0-deposit#112]
We already detect if there is insufficient ETH and display a warning, but if we are not in MAINNET config, we should also point to GoETH faucets.

Reasonable options include:

* _DappNode Faucet `206.25 ETH/9 days` [goerli-faucet.dappnode.net](https://goerli-faucet.dappnode.net/)_
* _Mudit's Faucet `87.50 ETH/9 days` [faucet.goerli.mudit.blog](https://faucet.goerli.mudit.blog/)_
* _Prylabs Faucet `32.50 ETH/request` [prylabs.net/participate](https://prylabs.net/participate)_

**Comment by caodinhdu1991** [comment]
Send me 320 eth 0x5e26Cc904E5339BB03Bd1c8E9289Fdb7518C9e39 
Thanks
