### ISSUE TITLE
Add a way to report issues

### ISSUE THREAD

**Issue by ericglau** [ethereum/eth2.0-deposit#134]
If someone is reading the instructions on the site and needs to report an issue, there is currently no way for them to figure out how (except on a [deposit file error](https://github.com/ethereum/eth2.0-deposit/blob/ef2b8a6ba28347f3251c0e9a25bd752de6562cad/src/pages/UploadValidator/index.tsx#L142) which links to the GitHub issues).  Consider adding a way to report issues (such as a link to GitHub or any other method of contact) in a more obvious place on the site.

**Comment by samajammin** [comment]
@CarlBeek @wackerow @ryancreatescopy this seems like a reasonable idea 😄  

Should we consider adding this prior to the translations effort in #308?
