### ISSUE TITLE
Staking infographic on Launchpad misleading

### ISSUE THREAD

**Issue by cooganb** [ethereum/eth2.0-deposit#143]
[On the Launchpad page,](https://medalla.launchpad.ethereum.org/) there's this bar chart following the amount of Goerli Eth staked. On the left side is the amount staked, on the right side is the remaining amount needed to start the Medalla network. Typically in a chart like this, the amount on the right side is the total.

However, for the screenshotted example below, it appears as though the whole network only requires 302336.0 Goerli Eth, rather than the 302k number being the outstanding remaining balance. Might want to consider changing wording around to reflect that. A minor thing, but I think clear visualization is important, particularly if we're trying to keep this open for less technical folks

<img width="90%" alt="Launchpad infographic" src="https://user-images.githubusercontent.com/8144425/88819291-698e2400-d185-11ea-985e-ca8eeb8f4f83.png">

**Comment by Battenfield** [comment]
Great point @cooganb. We should have resolved this in #125, but it looks like that did not make it into the release. We will get this wording updated in an upcoming release.

**Comment by cooganb** [comment]
@Battenfield Sounds good! Have you seen this issue as well? It's unrelated but a bit more pressing, I think:

https://github.com/ethereum/eth2.0-deposit/issues/142
