### ISSUE TITLE
Value displayed in statusbar includes invalid deposits

### ISSUE THREAD

**Issue by torfbolt** [ethereum/eth2.0-deposit#144]
The info statusbar on the landing page seems to display the total amount of ETH sent to the deposit contract address (compared with https://goerli.etherscan.io/address/0x07b39f4fde4a38bace212b546dac87c58dfe3fdc).

However, the actual genesis threshold is only reached if the number of **valid** deposits is high enough. So the statusbar should only display those. Otherwise, the statusbar will be at 100% before the genesis threshold is reached. According to my lighthouse client there are currently ~200 invalid deposits.

Edit: The statusbar on https://medalla.beaconcha.in/ seems to show the correct balance.

**Comment by CarlBeek** [comment]
Indeed it does, this is a known limitation. The number is also inflated by double-deposits / top-ups. This is done to preserve the property that Launchpad runs without a corresponding server. If we wanted to accurately track the number of deposits, we'd need to also run a server connected to a Beacon Node. While this is possible, we have try to avoid going down that path as it reduces the independence of this DApp.
