### ISSUE TITLE
Wrong deposited GoETH in congratulations page

### ISSUE THREAD

**Issue by PlanetaOTC** [ethereum/eth2.0-deposit#150]
There is a bug in the launchpad. If you for example want to setup 2 validators but only make the deposit in one of them and later click continue, the next page says that you have deposited 64 GoETH instead only 32. Not sure where or to who report this. Maybe some of the prysm devs know

**Comment by samajammin** [comment]
Thanks for reporting @PlanetaOTC!

Sorry for the long delay here 😅  but this was solved in https://github.com/ethereum/eth2.0-deposit/pull/366
