### ISSUE TITLE
Spadina: update prysm's document link

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-deposit#179]
Status-quo: https://github.com/ethereum/eth2.0-deposit/blob/a89f37a067e4739d0ec1afbf18f5c88ef9fb5b75/src/pages/Clients/Eth2/Prysm.tsx#L38

It looks like we have to link to the Spadina document site?

**Comment by prestonvanloon** [comment]
@har00ga can you help?

**Comment by hwwhww** [comment]
From ethstaker discord:

Peruzzi Today at 8:13 PM
> I didn't know I had to run my prysm beacon node with the flag --spadina. The spadina launchpad points to this guide: https://docs.prylabs.network/docs/testnet/medalla/
Eth2 launchpad onboarding | Prysm ETH2.0 Testnet
This section outlines the step-by-step process for how to join the Medalla multiclient testnet to run a Prysm eth2 beacon node and validator.

> So I configured my beacon node and my validator following the guide, and then I generated the deposit keys with --chain spadina

> I bet a lot of people did the same
So now my validator is stuck with the message "Deposited (An ETH1 deposit has been made, it will take around 8 hours until your deposit is processed by the beacon chain. Check out the deposits tab for more details)"

**Comment by hwwhww** [comment]
closing via #191 + EF devops
