### ISSUE TITLE
Set Eth2 clients installation instructions/links to ENV variables

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-deposit#189]
### Issue 
Like #179 and #188, the Eth2 client landing pages may be different for each testnet/mainnet.

### How to fix it
Launchpad has to add new ENV variables for different networks for these configurations.

**Comment by CarlBeek** [comment]
I think this is a reasonable solution in the short term, but looking forward, it may be worth reusing whatever mechanism we use to make support multiple languages.

**Comment by hwwhww** [comment]
closing via #191
