### ISSUE TITLE
"testnet" is used incorrectly in a few places

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-deposit#249]
"Testnet" is used a suffix to "Mainnet" on the mainnet production version of launchpad. Looks like the copy needs a few extra conditional handles of this case

![image](https://user-images.githubusercontent.com/1433595/98260299-c8172b00-1f48-11eb-86cd-5d396c17a2d4.png)

Thanks @adlerjohn for the report

**Comment by djrtwo** [comment]
ah, looks like this was fixed in dev recently
https://github.com/ethereum/eth2.0-deposit/pull/245

**Comment by hwwhww** [comment]
fixed in #245
