### ISSUE TITLE
beaconscan mainnet is unavailable 

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-deposit#250]
The `REACT_APP_BEACONSCAN_URL` on the servers are set to 
- Mainnet: https://beaconscan.com/validator
- Medalla: https://beaconscan.com/medalla/validator
- Zinken: https://beaconscan.com/zinken/validator

However,
- *All* these links are directing to Medalla now
- Mainnet and Zinken services are unavailable

Proposal:
- consider removing the beaconscan link now
- when it's up, set something like`BEACONSCAN_URL = IS_MAINNET ? 'https://beaconscan.com/validator' : 'https://beaconscan.com/${ETH2_NETWORK_NAME}/validator';` so we can drop the `REACT_APP_BEACONSCAN_URL`.
    - also for `BEACONCHAIN_URL`

**Comment by mtbitcoin** [comment]
We are wrapping up medella and should hv the mainnet up this week. Thank you

**Comment by hwwhww** [comment]
It since https://beaconscan.com/ is the mainnet now! Congrats! 🚀 
Closing this issue now.
