### ISSUE TITLE
BUG: Launchpad shows a grey screen in production

### ISSUE THREAD

**Issue by FBrinkkemper** [ethereum/eth2.0-deposit#256]
After the page is done loading it switches to a grey screen. This might be related to a possible chain split, see: https://twitter.com/cz_binance/status/1326456255515250693 

There are also console errors. The page should not be dependent on the ethereum mainnet for the informative part.

https://launchpad.ethereum.org/

**Comment by hwwhww** [comment]
Thanks for the report @FBrinkkemper We are looking into this.
 
It's likely because Infura is having issues due to the upgrade.
The launchpad index page is supposed to show the current deposit progress diagram which needs Ethereum Mainnet state.

**Comment by CarlBeek** [comment]
Thanks for raising this issue, we are looking into it urgently. Indeed, it looks like it is tied to eth1 problems, the page appears to crash at the moment it queries the deposit contract to show how many deposits have been made.

As @hwwhww mentioned, it is likely tied to Infura being down (which you can track here: https://status.infura.io/). You can run site locally if you wish to make deposits now. Note that if you plan on using Metamask as your wallet to make these deposits, you'll have to connect it to the RPC endpoint of your own Ethereum node as Metamask also depends on Infura. Instructions on how to configure Metamask for a custom RPC endpoint [here](https://metamask.zendesk.com/hc/en-us/articles/360043227612-How-to-add-a-custom-Network-RPC-and-or-Block-Explorer).

**Comment by FBrinkkemper** [comment]
Issue has been resolved it seems 👍
