### ISSUE TITLE
Separate PRICE_PER_VALIDATOR for mainnet & testnet

### ISSUE THREAD

**Issue by CarlBeek** [ethereum/eth2.0-deposit#34]
There will probably be separate `PRICE_PER_VALIDATOR`s for mainnet & testnet. Ideally this would be supported.

It is probably better to represent this as a quotient or factor as the deposit contract will compensate for this.

For example, if validators are depositing 3.2 ETH/validator, the deposit contract will store their deposit as 32 ETH, but the contract's balance will only increase by 3.2 ETH. Using a quotient, it is easier to determine represent this amount in the interface for total deposits etc.

**Comment by Battenfield** [comment]
Any update on if we are going with 3.2 or 32 GoETH for the testnet contract? What about the beacon chain threshold for testnet? @CarlBeek || @hwwhww

**Comment by hwwhww** [comment]
@Battenfield @CarlBeek
1. We plan to use `32` ETH as the min effective balance for the next *semi-official* multi-client testnet.
2. `MIN_GENESIS_ACTIVE_VALIDATOR_COUNT` is `2**14 (= 16,384)` on the latest spec. So far, no plan to assign a smaller number for the testnet.

**Comment by Battenfield** [comment]
Does this mean that the testnet deposit contract will also require 32ETH per validator? Or will it still be 3.2 ETH but the validator clients will interpreted the deposits as 32?

If we have no issue printing GoETH and providing proper faucets, I suggest going with 32ETH universally.

**Comment by hwwhww** [comment]
@Battenfield 32 ETH universally.

p.s. Görli social faucet provides 37.5 ETH/9 days: https://faucet.goerli.mudit.blog/ 😊

**Comment by CarlBeek** [comment]
Implemented via #90.
