### ISSUE TITLE
Top Up page improvements

### ISSUE THREAD

**Issue by samajammin** [ethereum/eth2.0-deposit#368]
Hey @CarlBeek - was looking through this Top Up feature with @wackerow & @ryancreatescopy. We have a few thoughts on potential improvements. Would love your input!

### 1 - There's a couple edge cases on this feature that lead to suboptimal UX

Overall our stance here is that we should provide warning / advisories but allow user to top up (up to a max of 33 ETH) if they choose to do so so they can ensure they have the max effective balance of 32 ETH.

**Scenario A: Validator balance is >31 ETH & <32 ETH. Effective balance is 31 ETH**

Current world: 
- Top up input auto-populates value to (32 ETH - their balance) BUT this value is <1 ETH which is invalid. This creates a confusing UX.
- User can't do anything... can't top up at all, button is disabled.

![image](https://user-images.githubusercontent.com/8097623/108895531-8ded9a00-75c8-11eb-9437-6a5d7185a8b0.png)

Proposal:
- Allow users to send 1 ETH or more (since contract requires minimum of 1 ETH). We add a warning but allow users to top up balance to be over 32 ETH, so that they can get effective balance to 32 ETH. If we want to add safeguards, we could force the maximum top up to bring them to <33 ETH.
- Auto-populate input value to 1 ETH (i.e. prevent value from ever being <1.0 ETH, since that is invalid)

**Scenario B: Validator balance is >32 ETH but <32.25 ETH. Effective balance is 31 ETH**

Similar situation here - if validator had dropped below effective 32 ETH balance at some point, there's a chance they may want to top up to push up that effective balance.

### 2 - Within the content we added a blurb explaining true balance vs. effective balance to make this more clear. We'd plan to link to [this article](https://www.attestant.io/posts/understanding-validator-effective-balance/). Any opposition to this? 

I was even thinking of reaching out to the author to see if we could add the content to the Launchpad so that we could translate the content. That might be an initiative for a future iteration of translations though as we'd need approval from the author & we'd have to add the page & configure it for translations.

**Comment by CarlBeek** [comment]
Looping in @Battenfield and @georgeweiler as I was discussing this with them in an out of band channel.

### 1 - Top-up amounts

I am coming around to the idea of allowing users to top-up to get their Effective Balance (henceforth EB) up to 32 ETH. We should not be deciding for users how they handle their validators. I like your proposal, @samajammin, but I think we can tweak it further based off of the hard requirements of validating.

* Minimum top-up: 1 ETH
* Max top-up (Whichever is greater):
    * 32.26 - effective balance
    * 1 ETH
* No top-ups for exited or slashed validators

Some user stories (modified from a a discussion with @Battenfield):

* User has 30.5ETH -> User can deposit 1-1.76ETH
* User has 31.26ETH -> User can only deposit 1ETH with an additional consent warning that 1ETH is the minimum
* User has been slashed -> can not deposit

### 2 - EB Content:

That article is really well done and really digs down into the technicals, I like it. I agree that we should ask to borrow some of the content to host ourselves and get translated. 👍

**Comment by samajammin** [comment]
Solve ind #363
