### ISSUE TITLE
FormattedDate renders 'Invalid Date' on iOS and Safari

### ISSUE THREAD

**Issue by minimalsm** [ethereum/eth2.0-deposit#388]
## Bug

FormattedDate component imported from from 'react-intl' is returning Invalid Date in production on iOS and Safari. I tried to quickly debug this myself however the FormattedDate works as expected on Safari when on localhost. 

May be relevant: https://github.com/formatjs/formatjs/issues/409

## Responsible Code

https://github.com/ethereum/eth2.0-deposit/blob/e5f4e0a27a5a2eb5093f2399673c62d56fcf081e/src/pages/Checklist/index.tsx#L338-L353

## Examples

on Safari iOS native app:

![IMG_4257](https://user-images.githubusercontent.com/62268199/112049297-57635a80-8b47-11eb-8a2d-b2229cb76cf7.jpeg)

on Safari iMac app:

<img width="1054" alt="Screenshot 2021-03-22 at 19 46 37" src="https://user-images.githubusercontent.com/62268199/112049309-5df1d200-8b47-11eb-9c6d-81ce22c995f5.png">

**Comment by hwwhww** [comment]
Thanks for the report! It has been fixed in the `master` branch and will be updated on the mainnet launchpad soon.

**Comment by samajammin** [comment]
Indeed, thanks for reporting this @minimalsm!

Confirmed this was fixed in https://github.com/ethereum/eth2.0-deposit/pull/385 - closing this out.
