### ISSUE TITLE
BoldCaps `ONLY WAY`, `CANNOT TRANSFER` and `CANNOT WITHDRAW` are not in the translation files

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-deposit#391]
Some `BoldCaps` words are not in the translation files.

https://github.com/ethereum/eth2.0-deposit/blob/5b76b313e9292ff4b25a588f05afec727d4e0366/src/pages/Acknowledgements/pageContent.tsx#L172-L174
![image](https://user-images.githubusercontent.com/9263930/112144603-67953b80-8c14-11eb-805c-e206750d5766.png)

https://github.com/ethereum/eth2.0-deposit/blob/5b76b313e9292ff4b25a588f05afec727d4e0366/src/pages/Acknowledgements/pageContent.tsx#L212-L215

![image](https://user-images.githubusercontent.com/9263930/112144536-52201180-8c14-11eb-8b47-4e0827a2842d.png)

**Comment by samajammin** [comment]
Thanks for catching! @wackerow assigning to you - could you please knock this out when you have a chance?
