### ISSUE TITLE
Overview page edge case

### ISSUE THREAD

**Issue by CarlBeek** [ethereum/eth2.0-deposit#40]
If you click the "Overview" item in the ToC the proceed button is swapped out with "I Accept" instead of "Continue".

![Screenshot 2020-04-09 at 2 53 59 PM](https://user-images.githubusercontent.com/12530043/78898038-6c002d00-7a73-11ea-9e41-e9d1ebd1caf2.png)

**Comment by wackerow** [comment]
No longer an issue as of #328 👍
