### ISSUE TITLE
Differentiate between invalid deposit file and bad deposit data

### ISSUE THREAD

**Issue by CarlBeek** [ethereum/eth2.0-deposit#41]
When submitting a `deposit_data.json`, there are two failure modes.  The first is when the user just uploads a random file which is not the correct file. The second is when a user uploads a `deposit_data.json` and the file is not valid/is corrupt/has invalid signature(s). The second state is much more severe and we should display a much more ominous error message encouraging users to get in contact opening an issue here or on `ethereum/eth2.0-deposit-cli`.

**Comment by sachayves** [comment]
Is it expected behaviour that one can submit the same `deposit_data` file twice?

**Comment by CarlBeek** [comment]
No. Using the same deposit data more than once, will result in double-deposits for validators which will just lock up all fund >=32 ETH until transfers are enabled. This is another class of incorrect deposit_data.

**Comment by Battenfield** [comment]
Solved in #108
