### ISSUE TITLE
Prominently display contract address (with links to block explorers?)

### ISSUE THREAD

**Issue by CarlBeek** [ethereum/eth2.0-deposit#43]
Currently the full deposit contract address is not displayed clearly anywhere. We've had discussions before around checking users actually use the correct contract, and there is no perfect solution, but it would be useful to at least display the current address.

Places where the address should be displayed:
* On hover over contract address in to left corner
* The phishing section of the summary page
* Transactions page

**Comment by torfbolt** [comment]
Maybe display it as an image file, to make it harder for any find-and-replace viruses that want to substitute anything that looks like an ethereum address.

**Comment by wackerow** [comment]
There is now a link to https://ethereum.org/en/eth2/deposit-contract/ both from the phishing page and the summary page immediately before you send any funds. Will close this for now for the sake of cleanup after recent upgrades and put on a list to potentially revisit if desired.
