### ISSUE TITLE
Congratulations Page

### ISSUE THREAD

**Issue by Battenfield** [ethereum/eth2.0-deposit#55]
High-level Congratulations page requirements:

- [x] Render the user the Contract Balance Progress Bar
- [ ] Render a completed transactions table(Designs Pending)
- [ ] Render the Client Validators info cards(Designs and Requirements Pending)
- [ ] Render additional resources cards

**Comment by CarlBeek** [comment]
Re-posing the below from #95 

The deposit page is rather sparse at the moment & it's time to address that. I'm opening this issue to track and ideate over what to include:

- [ ] Congrats artwork
- [ ] Change colour scheme on progress bar & handle post-deposit status à la #94
- [ ] Client suggestions (It looks like there are going to be 4 at launch, namely: Lighthouse, Nimbus, Prysm, Teku and I'd like to randomise the order in which they appear.) There should be links out to the various clients. 
- [ ] Show validator deposits on Eth2 explorers [Beaconscan](https://beaconscan.com/altona/validator/0x85db16729f897d347b1c19d289a08b6d8afad486f6e4be6f498ed95510569401d1a60cfbd606b07fe88de85be09a98fd) & [beaconcha.in](https://altona.beaconcha.in/validator/0x85db16729f897d347b1c19d289a08b6d8afad486f6e4be6f498ed95510569401d1a60cfbd606b07fe88de85be09a98fd)

**Comment by CarlBeek** [comment]
All of the above was implemented long ago
