### ISSUE TITLE
Errors when clicking copy for key generation commands.

### ISSUE THREAD

**Issue by econoar** [ethereum/eth2.0-deposit#59]
During step 4 of the key generation, there are buttons to copy out the commands. When I click them I get a TypeError. Screen shot is attached.
<img width="602" alt="Screen Shot 2020-05-08 at 9 00 20 AM" src="https://user-images.githubusercontent.com/5050615/81424164-621d2880-910a-11ea-9aee-a7f2045d886b.png">

Brave browser on MacOS

**Comment by CarlBeek** [comment]
Closed by #74
