### ISSUE TITLE
UI fixes for 'src/deposit.py'

### ISSUE THREAD

**Issue by ethers** [ethereum/eth2.0-deposit#64]
When #60 is fixed, the UI should be fixed:
https://github.com/ethereum/eth2.0-deposit/blob/dev/src/pages/GenerateKeys/MacInstructions.tsx#L28

Both Mac and Linux.  (check Windows too if applicable.)

This issue decouples simple/r UI fix, from code fixes in #60.

**Comment by hwwhww** [comment]
Hi! I just opened a PR on `deposit-cli` side for adding single script for different OS: https://github.com/ethereum/eth2.0-deposit-cli/pull/19

Any feedback would be appreciated!

**Comment by CarlBeek** [comment]
This was closed by #66
