### ISSUE TITLE
Windows commands for Key Generation page

### ISSUE THREAD

**Issue by Battenfield** [ethereum/eth2.0-deposit#67]
We need the windows version of our Mac/Linux instructions for generating validator keys.
- Dependency instructions and links
- terminal/PowerShell commands
- specify python version

![Screen Shot 2020-05-13 at 10 28 22 PM](https://user-images.githubusercontent.com/7051522/81896287-2995a880-9569-11ea-9322-83ccda762c6a.png)

**Comment by qnou** [comment]
python3 - https://docs.python.org/3/using/windows.html
python through choco - https://chocolatey.org/packages/python
pip3 - https://pip.pypa.io/en/stable/installing/   
pip through choco - https://chocolatey.org/packages/pip
git - https://git-scm.com/download/win  
git through choco - https://chocolatey.org/packages/git

Commands:
git clone https://github.com/ethereum/eth2.0-deposit-cli.git
cd eth2.0-deposit-cli
pip3 install -r requirements.txt
python setup.py install
python cli/deposit.py
