### ISSUE TITLE
Bump BLS library to align with Eth2 spec v0.12.0 version

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-deposit#78]
### Issue
The BLS signature spec was changed in [v0.12.0 update](https://github.com/ethereum/eth2.0-specs/pull/1799).

### How to fix it
I made a PR for deposit-cli: https://github.com/ethereum/eth2.0-deposit-cli/pull/33
The launchpad has to use the new [@chainsafe/bls version 2.0.0](https://www.npmjs.com/package/@chainsafe/bls) as well.

**Comment by CarlBeek** [comment]
Solved in #90
