### ISSUE TITLE
its very hard to get 3.2ETH from Goerli Test Network

### ISSUE THREAD

**Issue by netpi** [ethereum/eth2.0-deposit#82]
maybe, its the last step and the hardest step to get 3.2ETH from Goerli Test Network。
I can only get 0.05ETH once a time... wow !!!
it means that I will request 64 times from https://goerli-faucet.slock.it/ page. 
ti’s the hardest work...  😄

![image](https://user-images.githubusercontent.com/8254020/83496087-25ff9c80-a4eb-11ea-86e0-378c2d387990.png)

![image](https://user-images.githubusercontent.com/8254020/83496605-ed13f780-a4eb-11ea-8742-f119609debde.png)

if someone keep enough ETH for Goerli Test Network .
please send 3.2ETH to me, thanks very much 

`0x35d415bF0E6bbf8e10ebA814e10325c46a2CF009`

**Comment by sachayves** [comment]
@netpi you can request it one go from the authenticated faucet
 https://faucet.goerli.mudit.blog/

**Comment by netpi** [comment]
@sachayves 

thanks, I have successfully deposited

https://goerli.etherscan.io/tx/0x636e2c271bd491dadf437f0cb3c48726c1963e23716ef91f4a330d1d2ebcd1f6
