### ISSUE TITLE
Different chain-forks (Mainnet vs testnet etc)

### ISSUE THREAD

**Issue by CarlBeek** [ethereum/eth2.0-deposit#85]
Currently testnet & mainnet can be selected using envVars via `IS_MAINNET`. The complexity of different nets is not entirely captured by this model. and so it should be extended to support multiple configurations. Each net can vary in the following parameters:
* is_tesnet
* network name
* deposit amount
* deposit contract address
* fork version
* eth1 network (Goerlli vs mainnet etc)

These options are all properties of the network and should be swapped out depending on which one is active. As discussed in #83, all these parameters can be populated as envVars which possibly default to the mainnet configuration.

**Comment by CarlBeek** [comment]
Another parameter that could change between networks is the contract ABI (eg. with the existence of a drain function).

**Comment by Battenfield** [comment]
@CarlBeek and I discussed adding a dropdown to the Overview page, which will allow the ability to switch between configurations. 

Will we support new eth1 networks beyond Goerlli and Mainnet? 

Also, should we support custom configs that will override this new multiple config functionality? This will be useful if we have an "official" deployment, which should only be for the Testnet/Mainnet, not allowing users to switch to different configs. Or is the plan that there will be only one deployment for all eth2 networks?

**Comment by Battenfield** [comment]
Requirements as of now(pending questions above):

- Add dropdown to the first card of the Overview Page which allows the user to select between an "Eth2 Network" configuration
- Redux action to set eth2 network value in redux
- Once the user sets the eth2 network, set this name in the `<Appbar/>`
- Refactor all non-private variables in `envVars.ts` to choose from the network config (redux)
- Refactor all references of these variables in the former `envVars.ts` to pull from the new dynamic variable(if redux pull from store)
- Make additional mentions of the network name in all relevant places to ensure a user knows which eth2 network they are on
- Set dynamic contract address on the Summary page
- Update all references to isMainnet to the new config

**Comment by CarlBeek** [comment]
To address your questions:

* **Other eth1 networks:** I think not
* **Custom config support:** Ideally yes, but I don't think this needs to be too complicated: if someone wants to do this, they can manually edit the configs file.
* **Testnet/mainnet swapping once deployed:** I think we can lock it down and if someone want to change, they can be redirected (like block explorers do if you switch networks)

I think your list of requirements is fairly comprehensive

**Comment by Battenfield** [comment]
We started to look into the implementation, and it would be helpful if you could expand on this comment.
> Testnet/mainnet swapping once deployed: I think we can lock it down and if someone want to change, they can be redirected (like block explorers do if you switch networks)

Does this mean that we will have different Launchpad deployments for each eth2 network? For instance, do we want `witti.launchpad.ethereum.org` to be a deployment with a witti config similar to block explorers like`goerli.etherscan.io`? If so, this would be a much lighter of a lift as we could just have a configuration per deployment. For this case, we could have links or a dropdown that would navigate users to the appropriate deployment URL. 

Or

Do we want one testnet deployment with a dynamic config that is changed by a dropdown? This would mean that the user toggles the eth2 network on the Overview page and it switches the config in application state, allowing the user to access all eth2 testnets on this single deployment. We could also put in place a Mainnet environment variable which will override the testnet configs and not render the dropdown on the Overview page.

Either would work, we just need clarification on which as it drastically changes the UX and DevOps.

**Comment by CarlBeek** [comment]
Closed via #90
