### ISSUE TITLE
Progress bar after genesis threshold

### ISSUE THREAD

**Issue by CarlBeek** [ethereum/eth2.0-deposit#94]
After the genesis deposit threshold is reached the progress bar needs to change to reflect the new state of the network.

Currently:
* The "Launch threshold" is negative
* The label "Launch Threshold" does not match up with the value displayed before the threshold is reached. It should read "XXX ETH to go!" and I think "Already staked" is a more appropriate title for the current staking balance

![Screenshot 2020-07-08 at 5 01 56 PM](https://user-images.githubusercontent.com/12530043/86936986-fd4c7180-c13e-11ea-94ea-c3d44dc5e153.png)

I propose we fix the launch threshold in place and allow the current staking value to overtake it when the balance is larger like in the below image:

![Combined](https://user-images.githubusercontent.com/12530043/86937016-03dae900-c13f-11ea-8a7c-b2dc8fbdc767.png)

**Comment by Battenfield** [comment]
@georgeweiler

**Comment by CarlBeek** [comment]
Closed by #100
